#!/usr/bin/env bash

# lzx-note: Canonical repository paths after service/test separation.
PARP_RUNTIME_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
PARP_SERVICE_ROOT="$(cd -- "$PARP_RUNTIME_ROOT/.." && pwd)"
PARP_LZX_ROOT="$(cd -- "$PARP_SERVICE_ROOT/.." && pwd)"
PARP_REPO_ROOT="$(cd -- "$PARP_LZX_ROOT/.." && pwd)"
PARP_TEST_ROOT="${PARP_TEST_ROOT:-$PARP_REPO_ROOT/test}"
PARP_AUTOMATION_ROOT="${PARP_AUTOMATION_ROOT:-$PARP_TEST_ROOT/automation}"
PARP_AUTOMATION_CONFIG_ROOT="${PARP_AUTOMATION_CONFIG_ROOT:-$PARP_TEST_ROOT/configs/automation}"
PARP_RUNTIME_CONFIG_ROOT="${PARP_RUNTIME_CONFIG_ROOT:-$PARP_SERVICE_ROOT/configs/runtime}"
PARP_SERVICE_OUTPUT_ROOT="${PARP_SERVICE_OUTPUT_ROOT:-$PARP_SERVICE_ROOT/outputs/runtime_monitor}"
PARP_TEST_OUTPUT_ROOT="${PARP_TEST_OUTPUT_ROOT:-$PARP_TEST_ROOT/outputs}"
PARP_TOOL_ROOT="$PARP_LZX_ROOT/tool"
PARP_OPERATION_PREDICTOR_ROOT="${OPERATION_PREDICTOR_ROOT:-$PARP_TOOL_ROOT/operation_predictor}"

export PARP_RUNTIME_ROOT PARP_SERVICE_ROOT PARP_LZX_ROOT PARP_REPO_ROOT
export PARP_TEST_ROOT PARP_AUTOMATION_ROOT PARP_AUTOMATION_CONFIG_ROOT
export PARP_RUNTIME_CONFIG_ROOT PARP_SERVICE_OUTPUT_ROOT PARP_TEST_OUTPUT_ROOT
export PARP_TOOL_ROOT PARP_OPERATION_PREDICTOR_ROOT
