#ifndef MYSELF_KSWAPD_ERROR_H
#define MYSELF_KSWAPD_ERROR_H

#include <stddef.h>

enum reclaim_error {
    RECLAIM_OK = 0,
    RECLAIM_ERR_INVALID_ARGUMENT,
    RECLAIM_ERR_NO_MEMORY,
    RECLAIM_ERR_DOMAIN_NOT_FOUND,
    RECLAIM_ERR_DOMAIN_ALREADY_EXISTS,
    RECLAIM_ERR_DOMAIN_NOT_EMPTY,
    RECLAIM_ERR_PAGE_NOT_FOUND,
    RECLAIM_ERR_PAGE_ALREADY_EXISTS,
    RECLAIM_ERR_PAGE_STATE,
    RECLAIM_ERR_PAGE_TYPE,
    RECLAIM_ERR_PARSE,
    RECLAIM_ERR_EXECUTOR,
    RECLAIM_ERR_VALIDATION,
    RECLAIM_ERR_NOT_SUPPORTED,
    RECLAIM_ERR_INTERNAL
};

const char *reclaim_error_name(enum reclaim_error error);

#endif
